# Generated by Django 3.2 on 2023-03-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230329_1142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Review',
        ),
    ]
