# Generated by Django 3.2 on 2023-04-02 15:48

from django.db import migrations, models
import django.db.models.deletion
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230401_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AddField(
            model_name='title',
            name='category',
            field=models.ForeignKey(help_text='Категория произведения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, help_text='Описание произведения', max_length=510, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(help_text='Жанры произведения', related_name='titles', to='reviews.Genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='title',
            name='name',
            field=models.CharField(default=0, help_text='Название произведения', max_length=256, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='year',
            field=models.IntegerField(default=0, help_text='Год выхода произведения', validators=[reviews.validators.validate_year], verbose_name='Год выхода'),
            preserve_default=False,
        ),
    ]
